"""在 HTTP 边界把稳定的业务错误码映射为状态码。

数据流：应用层 ``AppError.code`` -> 映射表查询 -> FastAPI HTTP 状态码。
原理：业务层只描述“发生了什么”，传输层单独决定“如何通过 HTTP 表达”。
"""

from __future__ import annotations


_ERROR_STATUS = {
    "INVALID_JOB_ID": 400,
    "JOB_NOT_FOUND": 404,
    "IMPORT_PREVIEW_NOT_FOUND": 404,
    "ANALYSIS_NOT_STARTED": 404,
    "ANALYSIS_NOT_FOUND": 404,
    "CRITERIA_NOT_EXTRACTED": 404,
    "CANDIDATE_NOT_FOUND": 404,
    "CANDIDATE_NOT_ANALYZED": 404,
    "FILE_TOO_LARGE": 413,
    "UNSUPPORTED_FILE_TYPE": 415,
    "JOB_ALREADY_EXISTS": 409,
    "IMPORT_PREVIEW_ALREADY_EXISTS": 409,
    "IDEMPOTENCY_KEY_REUSED": 409,
    "ANALYSIS_ALREADY_RUNNING": 409,
    "CRITERIA_VERSION_CONFLICT": 409,
    "CRITERIA_NOT_CONFIRMED": 409,
    "EMPTY_RESUME_BATCH": 409,
    "ANALYSIS_STALE": 409,
    "ANALYSIS_NOT_READY": 409,
    "REVIEW_VERSION_CONFLICT": 409,
    "SELECTED_ROLE_REQUIRED": 422,
    "INVALID_PREVIEW_ID": 422,
    "NO_JOB_ROLES": 422,
    "CANDIDATE_LIMIT_INVALID": 422,
    "EMPTY_FILE": 422,
    "CSV_ENCODING_INVALID": 422,
    "CSV_REQUIRED_FIELDS_MISSING": 422,
    "CSV_MALFORMED": 422,
    "SELECTED_ROLE_NOT_FOUND": 422,
    "JD_REQUIRED": 422,
    "INCONSISTENT_JOB_DESCRIPTION": 422,
    "NO_VALID_RESUMES": 422,
    "SENSITIVE_CRITERION_FORBIDDEN": 422,
    "INVALID_LAYER": 422,
    "INVALID_SORT": 422,
    "ADOPT_LAYER_MISMATCH": 422,
    "OVERRIDE_LAYER_UNCHANGED": 422,
    "NO_SAFE_CRITERIA": 502,
    "CRITERIA_EXTRACTION_INCOMPLETE": 502,
    "LLM_UNAVAILABLE": 502,
    "LLM_REQUEST_REJECTED": 502,
    "LLM_RESPONSE_INVALID": 502,
    "LLM_RESPONSE_SCHEMA_INVALID": 502,
    "LLM_CONFIGURATION_MISSING": 503,
    "LLM_AUTHENTICATION_FAILED": 503,
    "STORAGE_CORRUPTED": 500,
    "ANALYSIS_COUNT_MISMATCH": 500,
}


def http_status_for(error_code: str) -> int:
    """只在 Web 边界把稳定业务错误码映射成 HTTP 状态。"""

    return _ERROR_STATUS.get(error_code, 500)
